### ISSUE TITLE
Publish docker image

### ISSUE THREAD

**Issue by jlegrone** [temporalio/temporalite#105]
**Is your feature request related to a problem? Please describe.**

Users should be able to quickly spin up Temporalite instances in container environments like Kubernetes, docker-compose, and various CI providers.

**Describe the solution you'd like**

Configure goreleaser to build & push container images for Temporalite to a temporalio owned container repository.

**Describe alternatives you've considered**

Docker compose users can already leverage Temporalite by building from source, eg.

```yaml
# docker-compose.yaml
version: '3.9'

services:
  temporalite:
    build: https://github.com/temporalio/temporalite.git#main
    ports:
      - 7233:7233
      - 8233:8233
```

**Additional context**
